blank_issues_enabled: false
contact_links:
    - name: My Privacy DNS Community Support
      url: https://mypdns.org/MypDNS/support/-/issues/
      about: For any support contact us at My Privacy DNS as we no longer
          trust Github or Gitlab https://mypdns.org/my-privacy-dns/porn-records/-/issues/1347
